<ul>
	<li><a href="<?php echo $this->baseUrl(); ?>/research/summary/code/<?php echo $this->company->COEM_TX_ID; ?>">Resumo</a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/research/cashflow/code/<?php echo $this->company->COEM_TX_ID; ?>"> Fluxo de Caixa </a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/research/balance/code/<?php echo $this->company->COEM_TX_ID; ?>">Balan&ccedil;o Patrimonial </a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/research/indicators/code/<?php echo $this->company->COEM_TX_ID; ?>">Indicadores</a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/research/doar/code/<?php echo $this->company->COEM_TX_ID; ?>">DOAR</a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/research/dre/code/<?php echo $this->company->COEM_TX_ID; ?>">DRE</a></li>
</ul>