
<?php echo $this->render('index/navbar.phtml'); ?>


<div id="main">
	<p>O SAINP é um sistema de código fonte aberto, oferecido sobre a licença GPL. O objetivo do sistema é ajudar o investidor não profissional a tomar decisões mais embasadas ao atuar no mercado financeiro.</p>
	<p>O código fonte do sistema está disponível pelo <a href="http://code.google.com/p/sainp/" target="_blank">Google Codes</a></p>
	<p>Nós aceitamos ajuda de quem queira colaborar a desenvolver o sistema:</p>
	<ul>
		<li><strong>Programador C++:</strong> Para criação de API para interface entre o Octave e o PHP</li>
		<li><strong>Programador PHP:</strong> Para criação das funcionalidades do sistema</li>
		<li><strong>Profissional de Finanças:</strong> para desenvolvimento das regras de negócio do sistema</li>
		<li><strong>Designer:</strong> Para criação dos templates e design gráfico do sistema</li>
		<li><strong>Outros:</strong> Elaboração da documentação do sistema</li>
	</ul>
    <p> Se estiver disposto a ajudar, entre em contato pelo email <a href="mailto:christian.daquino@sainp.net84.net">christian.daquino@sainp.net84.net</a></p>
</div>