<?php echo $this->render('index/navbar.phtml'); ?>

<div id="main">

<table border="1" cellpadding="0" cellspacing="0" style="border-color: #F0F0F0;">
    <thead>
       <tr>
          <th>
             Ação
          </th>
          <th>
             Período
          </th>
          <th>
             Descrição
          </th>
       </tr>
   </thead>
   <tbody>
       <tr>
          <td>
             <a href="<?php echo $this->baseUrl(); ?>/index/historic">Cotações Históricas</a>
          </td>
          <td>
             Primeiro dia últil de cada mês
          </td>
          <td>
             Atualiza a tabela bov_historico com a cotações do último dia útil de cada mês
          </td>
       </tr>
   </tbody>
</table>

</div>