
<?php echo $this->render('index/navbar.phtml'); ?>

<div id="main">
	<p>Bem Vindo ao SAINP - Sistema de Apoio ao Investidor Não Profissional.</p>
	<p>O SAINP é um sistema <b>gratuito</b> de análise fundamentalista, de código fonte aberto sob a licença GPL e que ainda está em fase de desenvolvimento.</p>
    <p>Ainda não é cadastrado? <a href="<?php echo $this->baseUrl(); ?>/index/register">Cadastre-se <b>gratuitamente</b> aqui</a>.</p>
    <p>Você também pode contribuir com o desenvolvimento do sistema. Acesse nossa página no <a href="http://code.google.com/p/sainp/" target="_blank">Google Codes</a> ou entre em contato por <a href="mailto:christian.daquino@sainp.net84.net">Email</a></p>
</div>

<?php //echo $this->render('/index/portal_footer.phtml'); ?>
