<div id="navBar">
	<div id="sectionLinks">
		<ul>
			<li><a href="<?php echo $this->baseUrl(); ?>/index/index">Página Inicial</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/index/register">Cadastre-se</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/public/wordpress/" target="_blank">Blog/Atualizações</a></li>
			<li><a href="<?php echo $this->baseUrl(); ?>/index/about">Sobre o SAINP</a></li>	
			<li><a href="<?php echo $this->baseUrl(); ?>/index/require">Especificação do Sistema</a></li>
			<li><a href="<?php echo $this->baseUrl(); ?>/mailto:christian.daquino@sainp.net84.net">Contato</a></li>
		</ul>
	</div>
</div>