

<div id='main2'>
    <h2>Termos de Uso</h2>
    <p>O acesso do usuário a este Site e a utilização do mesmo ficam sujeitos aos termos e condições abaixo:</p>
    <ol>
    	<li>Este sistema é um protótipo e está disponível em caráter experimental aos usuários. Qualquer decisão tomada pelo usuário é sua total e completa responsabilidade</li>
    	<li>O SAINP não se responsabiliza com a precisão das informações apresentadas pelo sistema</li>
    </ol>

    
    <form action="../index/regforward" method="post">
      <input name="accept" type="radio" id="accept" value="yes" />
      <label for='accept'>Concordo</label>
      
      
      <br>
      <input name="accept" type="radio" id="dontaccept" value="no" />
      <label for='accept'>Não Concordo</label>
      
      <br>
      <input type="submit" name="salvar" id="salvar" value="Avancar">
    </form>
</div>

