<?php echo $this->render('index/navbar.phtml'); ?>

<div id="main">
	<h3>Especificação do SAINP:</h3>
	<ul>
		<li>PHP 5.2</li>
		<li>MySQL</li>
		<li><a href="http://framework.zend.com/" target="_blank">Zend Framework</a></li>
		<li><a href="http://www.gnu.org/software/octave/" target="_blank">Octave</a></li>
		<li><a href="http://hara.mimuw.edu.pl/weboctave/web/" target="_blank">Weboctave</a></li>
	</ul>

</div>