<ul>
	<li><a href="<?php echo $this->baseUrl(); ?>/portfolio/portfolio"> Carteira </a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/portfolio/optimization"> Otimizacao </a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/portfolio/protection"> Protecao </a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/portfolio/buy"> Compra </a></li>
	<li><a href="<?php echo $this->baseUrl(); ?>/portfolio/sell"> Venda </a></li>
</ul>