<div id='protection'>

<form id='prot' action='<?php echo $this->baseUrl(); ?>/portfolio/updateprotection' method="post">
<label for='protect'>% de Protecao</label>
<select name='protect' id='protect'>
	<option value='0%'>Sem Proteção</option>
  <option value='5%'>5%</option>
  <option value='10%'>10%</option>
  <option value='15%'>15%</option>
  <option value='20%'>20%</option>
  <option value='25%'>25%</option>
  <option value='30%'>30%</option>
  <option value='35%'>35%</option>
  <option value='40%'>40%</option>
</select>
<input type='button' name='proteger' id='submit' value='submit'>
</form>

</div>