<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Expires" content="0">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<META http-equiv="CONTENT-LANGUAGE" CONTENT="pt-br">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<meta name="author" content="Christian D'Aquino">
<meta name="description" content="SAINP - Sistema de Análise Fundamentalista">
<meta name="keywords" content="sainp, análise, analise, fundamentalista, análise fundamentalista, analise fundamentalista, mercado, capitais, mercado de capitais, bovespa, ibovespa, finanças, financeiro, hedge, hedging, investimento, investimentos, investidor, ações, opções, ticker, bmef, bm&f, google code, opensource, open source, software livre, software, livre, php, mysql, octave, weboctave, zend framework, MCV, economatica, GPL">

<meta name="google-site-verification" content="9RMYoDAbxjSR0jU69ec1rOcNjEil8F-lTEU0uIkFMa8" />
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

<title>SAINP - Sistema de Análise Fundamentalista</title>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/public/styles/portal.css'); ?>
</head>

<body>
	<!-- Google Analytics -->
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-9796408-3']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>

<div id="container">
	<div id="masthead">
		<div id="logo">
			<img src="<?php echo $this->baseUrl(); ?>/public/pictures/sainp_logo_beta_pequeno.png" alt="SAINP" />
			<h1>Sistema de Análise Fundamentalista</h1>
		</div>

		<div id="login">
			<?php echo $this->loginForm; ?>
		</div>
	</div>
	
	<div class="clear"></div>

	<div id="content">
		<?php echo $this->layout()->content; ?>
	</div>

	<div class="clear"></div>


	<div id="siteInfo">
	  <p>&copy;2010 SAINP | <a href="<?php echo $this->baseUrl(); ?>">Página Inicial</a> | <a href="<?php echo $this->baseUrl(); ?>/index/about">Sobre o SAINP </a> | <a href="mailto:christian.daquino@sainp.net84.net">Contate-nos</a> | <a href="http://code.google.com/p/sainp/" target="_blank">Google Codes</a> | <a href="https://sourceforge.net/projects/sainpfinance/" target="_blank">Sourceforge</a> | <a href="http://www.000webhost.com/" target="_blank">000Webhost</a> | <a href="<?php echo $this->baseUrl(); ?>/index/dashboard">Dashboard</a></p>
	</div>
</div>

</body>
</html>