<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="Expires" content="0">
	<meta http-equiv="Pragma" content="no-cache">
	<meta http-equiv="Cache-Control" content="no-cache">
	<META HTTP-EQUIV="CONTENT-LANGUAGE" CONTENT="pt-br">
	<meta http-equiv="content-Type" content="text/html; charset=iso-8859-1" />
	<meta name="author" content="Christian D'Aquino">
	<meta name="description" content="SAINP - Sistema de Análise Fundamentalista">
	<META NAME="ROBOTS" CONTENT="NONE">
	<link rel="shortcut icon" href="../favicon.ico" type="image/x-icon" />
	
    <title>SAINP - Sistema de Análise Fundamentalista</title>
    <link href="<?php echo $this->baseUrl(); ?>/public/styles/system.css" rel="stylesheet" type="text/css" />
    
</head>
<body>

<div id="container">
	
	<?php echo $this->render('systemHeader.phtml'); ?>	

	<div id='controllerNav'>
	 <?php
	 if (isset($this->navigation)) {
		echo $this->render($this->navigation); 
	}
	?>
	</div>

	<?php echo $this->render('systemNavigation.phtml'); ?>
	
	<div id='main'>
		<?php echo $this->layout()->content; ?>
	</div>
</div>

    
    
</body>
</html>
